### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by NicholasCunningham** [WaterbendingToph/cs414-f20-public_class_TeamD#17]
Acceptance criteria: 
- A registration page with UI that talks to the backend. 
- Users are stored in and can be accessed from a database.
- Registration is denied when the username is taken or the password is invalid. 
- Registration is successful when the username is free and the password is valid.
- Successful registration yields a confirmation, log-in, and page transfer upon success.

**Comment by victorem1** [comment]
Acceptance criteria: User can register. Entails a registration page, a database of users to be put in, denial when the username is taken or the password is invalid, and a confirmation plus page transfer plug log in upon success.
